"""Add age and personalization_preferences to user

Revision ID: 286ce921ec33
Revises: ad5bebe59b3e
Create Date: 2026-03-23 22:28:12.904811
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '286ce921ec33'
down_revision: Union[str, None] = 'ad5bebe59b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('personalization_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personalization_preferences')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
