"""update onboarding fields

Revision ID: 7ac4f8da2b5d
Revises: 286ce921ec33
Create Date: 2026-03-23 22:33:14.382299
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '7ac4f8da2b5d'
down_revision: Union[str, None] = '286ce921ec33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('primary_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('relaxation_methods', sa.JSON(), nullable=True))
    op.alter_column('users', 'age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('users', 'music_genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('music_genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('users', 'age',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('users', 'relaxation_methods')
    op.drop_column('users', 'primary_reason')
    # ### end Alembic commands ###
