"""Add global streak fields to user model

Revision ID: d9509398cf1d
Revises: 87771b3b8877
Create Date: 2026-04-03 22:14:39.899458
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'd9509398cf1d'
down_revision: Union[str, None] = '87771b3b8877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_streak_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('longest_app_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'longest_app_streak')
    op.drop_column('users', 'app_streak_count')
    # ### end Alembic commands ###
